# ----------------------
# Stage 1: Builder
# ----------------------
  FROM oven/bun:1 AS builder
  WORKDIR /app
  
  COPY package.json bun.lockb* ./
  COPY packages ./packages
  RUN bun install
  
  COPY turbo.json .
  COPY apps/Scraper/package.json ./apps/Scraper/package.json
  WORKDIR /app/apps/Scraper
  RUN bun install
  RUN bunx puppeteer browsers install chrome
  COPY apps/Scraper /app/apps/Scraper/
  RUN bunx tsup index.ts --out-dir=dist --minify --dts --format=esm --clean
  WORKDIR /app
  RUN bun run node_modules/puppeteer/install.mjs
  
  # ----------------------
  # Stage 2: Runtime
  # ----------------------
  FROM oven/bun:1 AS runtime
  RUN apt-get update && apt-get install -y \
  ca-certificates \
  fonts-liberation \
  libappindicator1 \
  libasound2 \
  libatk1.0-0 \
  libatk-bridge2.0-0 \
  libc6 \
  libcairo2 \
  libcups2 \
  libdbus-1-3 \
  libexpat1 \
  libfontconfig1 \
  libgbm1 \
  libgcc1 \
  libglib2.0-0 \
  libgtk-3-0 \
  libnspr4 \
  libnss3 \
  libpango-1.0-0 \
  libpangocairo-1.0-0 \
  libstdc++6 \
  libx11-6 \
  libx11-xcb1 \
  libxcb1 \
  libxcomposite1 \
  libxcursor1 \
  libxdamage1 \
  libxext6 \
  libxfixes3 \
  libxi6 \
  libxrandr2 \
  libxrender1 \
  libxss1 \
  libxtst6 \
  lsb-release \
  wget \
  xdg-utils \
  --no-install-recommends && rm -rf /var/lib/apt/lists/*

  WORKDIR /app
  # ENV NODE_ENV=production
  ARG NODE_ENV
  ENV NODE_ENV=${NODE_ENV}

  ARG AWS_ACCESS_KEY_ID
  ARG AWS_SECRET_ACCESS_KEY

  ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  ARG SOURCEONE
  ARG SOURCETWO

  ENV SOURCEONE=${SOURCEONE}
  ENV SOURCETWO=${SOURCETWO}
  
  # 1) Copy the built files
  COPY --from=builder /app/apps/Scraper/dist ./dist
  
  # 2) Copy node_modules
  COPY --from=builder /app/node_modules ./node_modules
  
  # 3) IMPORTANT: Copy the local packages so symlinks aren't broken
  COPY --from=builder /app/packages ./packages

  COPY --from=builder /root/.cache/puppeteer /root/.cache/puppeteer
  
  EXPOSE 3000
  CMD ["bun", "run", "./dist/index.js"]
  